### ISSUE TITLE
keymon: command not found

### ISSUE THREAD

**Issue by seetee** [gimpscape/gimpscape-ppa#1]
Added the PPA, installed the keymon-package (including the automatically installed python3-gi-cairo and python3-xlib). But then I can not start the program with either "keymon" or "key-mon". Both gui and cli returns "command not found". 

Am I being stupid and missing something obvious?

**Comment by raniaamina** [comment]
Let us check soon, can you give some information about your OS?

**Comment by raniaamina** [comment]
Fixed in latest commit https://github.com/gimpscape/gimpscape-ppa/commit/506e8f6fa245a470d5907dfe1d4b14d2ad7fc813 (v1.19-2), now you can update it from this repo. Thanks for your report :")

**Comment by seetee** [comment]
Thank you! It works great now. That was quick. I did not even have time to answer your query. :-)

**Comment by raniaamina** [comment]
No worries, thanks for reporting the problem, much appreciated @seetee!
